dataset:
  modality: Af
  folder: data/MEEI/MEEI/csvs/
  csv_path: images_3.csv
  image_col: 'file_path_image'
  ga_col: 'file_path_ga_seg'
  vessel_col: 'file_path_vessel_seg'
  patient_id_col: 'study_id'
  laterality_col: 'Laterality'
  modality_col: 'Procedure'
  examdate_col: 'ExamDate'
  size_x_col: 'XSlo'
  size_y_col: 'YSlo'
  scale_x_col: 'Scale_X'
  scale_y_col: 'Scale_Y'

models:
  segmentation:
    ga:
      hist_eq: True
      weights: src/weights/ga_seg/epoch=32-step=1023.ckpt
    vessel:
      hist_eq: False
      weights: src/weights/vessel_seg/
  registration:
    method: affine
    input: image
    reg2start: True
    tps: 0.
    size: 256
  device: cuda:1

results:
  folder: meei_05192025